### ISSUE TITLE
Error and hang when populating by loss of focus

### ISSUE THREAD

**Issue by JupiterJesus** [kit-nya/anki_furigana#1]
Sometimes when I tab out of my Kanji field, I get an error box. I can dismiss the box, but the progress popup, "Processing", remains on the screen forever. I can't interact with Anki at all. To regain control, I have to open the task manager and force kill the anki process. The result of "copy debug info" is below.

An example of a word that causes this problem is 十月.

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 104, in wrapped_done
  File "aqt.progress", line 230, in finish
  File "aqt.progress", line 275, in _closeWin
TypeError: isdeleted() argument 1 must be PyQt6.sip.simplewrapper, not None

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Japanese ['1344485230', 2024-04-22T01:46, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-30T14:58, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-04-15T15:11, 'None', mod]
Japanese Automatic Word Definition  rt Reading Offline ['1657733540', 2024-04-14T01:30, 'None', mod]
Japanese Pitch Accent ['148002038', 2023-05-07T06:01, 'None', '']
Simple Forvo Audio Downloader ['560814150', 2023-10-31T09:47, 'None', mod]

===IDs of active AnkiWeb add-ons===
111623432 1344485230 148002038 1657733540 1739176371 560814150

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
External Note Editor for the Browser ['1996266159', 2020-03-31T13:59, 'None', '']

**Comment by kit-nya** [comment]
Hi,

Thanks for the report. I've tried to replicate the problem on my end using the word you've provided but I'm not getting any issue at all. I've tried both on the same version you're using as well as the latest version of anki.

Are you able to try disabling all addons and then re-enabling one by one until you get the problem occur? I suspect it might be an issue with the addons conflicting, or perhaps an entirely different addon. Or perhaps, disable my addon first and see if you still get the error, at least it'll rule out that as causing the problem!

Thanks,

Kit

**Comment by JupiterJesus** [comment]
Sure thing I’ll try and get back to you
________________________________

**Comment by JupiterJesus** [comment]
Okay, the example I gave above no longer causes the hang. I made no changes to any of my addon settings, 十月 just works now.

I noticed it fails a lot on forms that aren't the "primary". For example, umai is usually written as 上手い (good at). However, if I enter it as 美味い (for the word delicious) I get a hang. The actual dictionary entry is under 上手い, and 美味い is listed in "other forms" and is referenced in def. 2 (delicious). 

If I disable your addon, creating a new note with adding a NEW NOTE with 美味い doesn't freeze the app. 
If I disable every addon but keep yours enabled, adding a NEW NOTE with 美味い doesn't freeze the app. Editing an existing note, however, DOES freeze the app.

Continuing down this road, I right-clicked the existing note that broked and created a copy, then cleared all fields. Adding 美味いand tabbing out worked just fine.

Creating a copy, as above, and leaving all fields intact, then putting 美味い into the kanji field and tabbing out WORKED.

Editing the existing note in-place in the deck browser, tabbing out of the 美味い kanji field freezes the app.

Sometimes it hangs on kanji that are actually multiple words or that have an お attached (when the お isn't actually part of the dictionary listing).

I went back to an existing note for 十月 and tabbed out of the kanji field in the deck browser and it froze up.

Conclusion - this bug only occurs when editing an existing note using the deck browser. The only addon enabled is anki_furigana.
![Screenshot 2024-05-16 090556](https://github.com/kit-nya/anki_furigana/assets/19232339/632641fd-1e1a-4286-94dd-272fbadfd707)

**Comment by JupiterJesus** [comment]
Another example, but the behavior here is different. Using the word "お風呂" (ofuro) in a popup editor window during reviews cause an error message and freeze. Using お風呂 in the "add new card" dialog produces no answer BUT it doesn't freeze.

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 104, in wrapped_done
  File "aqt.progress", line 230, in finish
  File "aqt.progress", line 275, in _closeWin
TypeError: isdeleted() argument 1 must be PyQt6.sip.simplewrapper, not None

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Japanese ['1344485230', 2024-04-22T01:46, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-30T14:58, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-04-15T15:11, 'None', mod]
Japanese Automatic Word Definition  rt Reading Offline ['1657733540', 2024-04-14T01:30, 'None', mod]
Japanese Pitch Accent ['148002038', 2023-05-07T06:01, 'None', '']
Simple Forvo Audio Downloader ['560814150', 2023-10-31T09:47, 'None', mod]

===IDs of active AnkiWeb add-ons===
111623432 1344485230 148002038 1657733540 1739176371 560814150

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
External Note Editor for the Browser ['1996266159', 2020-03-31T13:59, 'None', '']

**Comment by kit-nya** [comment]
Hrmm, I suspect it's perhaps because the term searches are crazy inefficient which is why it seems to happen at random. I'll refactor that part of the code and hopefully it'll solve the problem. I'll post an update in the next few days to Ankiweb; and I'll let you know here when I do.

Thanks heaps for the report!

-Kit

**Comment by kit-nya** [comment]
I've refactored the code and uploaded a new copy to ankiweb. Let me know if you still have issues!

**Comment by JupiterJesus** [comment]
Haven't encountered (or looked for) any crashes, but the reading generation speed has increase dramatically. No more one-second pause when tabbing out. Much better! Thanks for the update.
