### ISSUE TITLE
Create HTML ordered list for definitions

### ISSUE THREAD

**Issue by HeyyD** [kit-nya/anki_furigana#3]
Instead of hardcoding the definitions field formatting, the field could be created as an ordered list. This way there user can style the cards more flexibility using own css styles.

``` diff
diff --git a/kanji_furi.py b/kanji_furi.py
index ad1c799..2ecae15 100644
--- a/kanji_furi.py
+++ b/kanji_furi.py
@@ -64,7 +64,7 @@ def build_dict_from_xml(root):
         for i, sense in enumerate(entry.iter('sense'), start=1):
             glosses = [gloss.text for gloss in sense.iter('gloss')]
             gloss_text = '; '.join(glosses)
-            senses[i] = f"{i}: {gloss_text}"
+            senses[i] = f"{gloss_text}"
         reb = entry.findall('r_ele/reb')[0].text.strip()
         for ke in keb_entries:
             if ke not in output:
@@ -78,7 +78,11 @@ def get_senses(dict_item, limit=5):
     for number in numbers:
         if number in dict_item["senses"]:
             arry.append(dict_item["senses"][number])
-    return "<br>".join(arry)
+    if len(arry) == 1:
+        # Return the single item as plain text
+        return arry[0]
+
+    return f"<ol>{''.join(f'<li>{item}</li>' for item in arry)}</ol>"

 def search_def(root, keb_text, def_limit=0):
     return_val = ""
```

Example of styled ordered list

![image](https://github.com/user-attachments/assets/f47e3306-810e-4f90-95b4-8a4756b42c12)

**Comment by kit-nya** [comment]
Hi!

Thanks for the feedback! The hard coding was working for what I wanted, but if there's a better way to do it that works for everyone then I'm all for it!

I'll merge this change tomorrow and publish an update.

Edit:forgot to say thanks for providing the example code!

**Comment by kit-nya** [comment]
こんにちは～

I've updated the addon with your suggestion as above. I've added a setting to use the formatted list as you've provided which needs to be toggled on first. I've left it off by default as to not randomly annoy anyone who's used to the existing format.

Thanks again for the suggestion!
